# Parse records text file

use warnings;
use strict;

my $datafile = "data.txt";
my $recordsep = '-=-\n';

open my $DATAFILE, '<', "$datafile" or die ("Unable to open file $datafile. $!\n");
{
	local $/ = 
	$recordsep;
	print "#\n# Host file - Generated by $0\n# Do not edit by hand!";

	my %record;
	while (<$DATAFILE>) {
		chomp;
		# split into key1, value1 ... 
		%record = split /:\s*|\n/;
		print "$record{address}\t$record{name} $record{aliases}\n  "
	}
close $DATAFILE;
}